### ISSUE TITLE
Workflow for publishing blogs

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#12]
Steps you think which should be followed to put all the data from the repository to the web page, and how you think your team would help you with the data curation part from the repo.

**Comment by reddymahendra52** [comment]
* First I think the markdown while converting into HTML we should try to make  some standards like:
     1. Keeping H1 for Main heading
     2. H2 for sub topics and H3 for sub sub topics
     3. Use paragraph and lists elements only
* And other than those created standard elements if their are any extra elements we should try to embed them into standard elements or try to convert them.
* If we make standards it will be easy to style them all using one main stylesheet and pages will look uniform throughout.
* If any standards are created I expect my teammates to help converting the given markdown into HTML

**Comment by akshayadme** [comment]
- Initially teammate should know how the content should be placed so that the end-users can understand what the author wants to teach them.

- Next point is teammate must have written the content in a right manner so that it will be easy for me to add content in a web page efficiently which means category, sub category, images, tables, data everything must be proper. 

- If any software is required then he must have knowledge which  software we have to add in our web page.

- He must be in contact whenever I need him for assistance.

**Comment by manvi-123894** [comment]
- Firstly, there should be a mutual understanding among the team members about how a particular element has to be designed like elements having equal importance should be designed in a similar manner to avoid haphazard design. 

- I would want my teammate to assist me in converting the markdown and ipynb file into HTML.

- Also I would want the teammate to give honest feedback about how the web page looks and how it can be improved.

**Comment by Ansuman9020** [comment]
- The datas in the repo must be arranged systematically so that a user reading it maynot find it difficult while going through the information.
- A single person can't be able to perform certain task itself, teammates play a key role by supporting eachother. While in a team a general overview will gain as it will be combined with different multiple ideas.
- Coverting the markdown and ipnynb file to HTML codes need assitance of the teammates. Task may not difficult but working in team lead to finish it in less time and effective outcome.

**Comment by chirag0821** [comment]
- It is difficult to convert and merge .ipynb file and .md file into the html without help of teammates.
- If teammates provide merge of .ipynb and .md file the task will become easy. 
- Teammate should know how the page will look like.
- Making standards for the element like heading will reduce the efforts.
- The content should be proper and teammate must be in contact.
