### ISSUE TITLE
"Search" in static pages

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#13]
Search for available options to enable "Search" on static webpages.

> In a way that it can match the keywords and show the blogs available with that keyword on the site.

Some of the methods are [given here](https://www.addsearch.com/blog/how-to-add-search-to-you-static-website/) and [here](https://dev.to/albogdano/implementing-full-text-search-for-your-static-site-4ool) , you can check if anyone can work with our website, and search for other options as well, like if we can use [elastic search](https://www.elastic.co/what-is/elasticsearch) here.

> Choose the one which is good for static pages and Github pages.

**Comment by reddymahendra52** [comment]
* Today's task was to enable a search bar on our static webpage
* I tried to implement the [Para](https://paraio.com/) but was not able to successfully implement it
* Then tried to implement [Lunr](https://lunrjs.com/) but was not able to successfully implement that also
* I found a codepen with Lunr the link is here: -->[Pen](https://codepen.io/a-luna/pen/GRooENM?editors=0110)
* I exported the file and tried it which works (The codepen file)
[dist.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5366637/dist.zip)
* And tried to implement the above code snippets on one of our pages but it is not opening properly maybe due to some bugs
* I am adding the file file with no images due to poor network it is taking time
[SE.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5366739/SE.zip)

**Comment by manvi-123894** [comment]
- Today's task was to figure out how to add search functionality to a static website.

- I've worked with vanilla Javascript where filter can be used to add search functionality.

- An array of objects can be created and each object will have some keywords and based on these keywords the search results can be filtered.

- I read about jekyll and other static web page generators but couldn't really figure out how to implement the search functionality using those tools.

**Comment by chirag0821** [comment]
- I searched about SaaS but couldn't find any resources to implement it.
- I think we can use JSON to store the keywords.
- Then by using Fetch API and changing html through javascript we can implement the given task.
- But i think it will take time to search or render on webpage because it is searching into the the JSON array.

**Comment by akshayadme** [comment]
- I have read some of the articles for implementing search functionality in static websites but I can't get any conclusion for that.

- There are some techniques by which we can implement search in static website but for that we have learn new framework and its a bit tricky and time consuming.

- The links you have suggested if we implement it may be  affective or may be not for some of the times. 

- If there is requirement for search functionality it will be better to be use dynamically by using server and database.

**Comment by Ansuman9020** [comment]
- I do find it more confusing about the search task given yesterday.
- As it is new to me, I found it difficult to know and research about it.

**Comment by manvi-123894** [comment]
- I've tried to implement the search functionality using Vanilla Javascript.

- I've created a painting catalog. In this, one can write the name of the painting and when the user clicks the search button then the result is displayed on the web page.

- In this, I've created an array of objects containing all the required information of the painting according to which HTML is dynamically created in javascript depending on the input given by the user. 

- For the search functionality here I've only used the name of the painting but for our blog page, we can also include the keywords in the filter function so that even if a user doesn't provide the exact topic of the blog then also the related blogs could be displayed if even one of the keyword is matching. Then, we can provide the link to the complete article directing it to another HTML page.

[Search_Javascript.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5370804/Search_Javascript.zip)

**Comment by Ansuman9020** [comment]
https://www.youtube.com/watch?v=M3PbUwgEecU
https://www.youtube.com/watch?v=-bqDzd1-Prc

- This may help us in implementing workable search task. I request everyone to watch this two videos.

**Comment by reddymahendra52** [comment]
* Today's task was to implement yesterday's ideas.
* I was successfully able to implement and integrate it.
* Uploading a file without images for quicker upload
* Working searchbar 👇 
[Working SE.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5372440/Working.SE.zip)

**Comment by akshayadme** [comment]
- As search option has to be implemented in the static website and manvi and mahendra has implemented it. I have tried it.
- I think mahendra's idea is bit difficult because its based on new framework lunr.js and we don't have knowledge about it. If we add and we get any errors in that then we cannot resolve as we don't have understanding of it.
- I have worked on manvi's idea which is basic JavaScript and it will be easy to debug and integrating is easy. I have implemented it but its not completed yet.
