### ISSUE TITLE
Analyze the website

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#18]
The website [Devincept.codes](https://devincept.codes/) just got hosted, there are many things which can be done to make it more smooth for web and mobile. Today try to analyze the website and see what improvements can be made.

1. Go [here](https://developers.google.com/speed/pagespeed/insights/) and put the URL of website ***(devincept.codes)***
2. It'll take a moment and will analyze the website.
3. Check for both, **Mobile** and **Desktop**
4. It will show changes which can be done to improve the performance.
5. Analyze from the analysis made, and comment below the changes which can easily be done to improve the performance.

**Comment by reddymahendra52** [comment]
**For Mobile:**
* For mobile website the score is 44
* Which according to me is less i think it can be greatly improved by using the next-gen  image formats like JPEG 2000, JPEG XR, and WebP which will save a lot of time.
* And i  also noticed that we are using the same size images for both desktop and mobile which is also increasing the time, if we use same images of different sizes which is different for desktop and different for mobile that can also reduce the load time and increase speed.
* And using MPEG4/WebM videos for animations and PNG/WebP for static images instead of GIF to save network bytes can also increase the speed.

**For Desktop:**
* The score is good which is 84
* It can also be increased if we use next-gen  image formats like JPEG 2000, JPEG XR, and WebP 

**Query**
* I am not sure if the Hubspot newsletter is showing every time i load the page i don't know if it is supposed to work that way or not. Instead maybe we can put the newsletter tab at the end of the page if that's possible.

**Comment by manvi-123894** [comment]
- Score for Mobile Version is 23.

- Score for Desktop Version is 77.

**According to suggestions shown :**

- Image formats like JPEG 2000, JPEG XR, and WebP should be used to provide better compression than PNG or JPEG and for faster downloads and less data consumption. 

- Responsive Images should be used which means generating multiple versions of each image, and then specifying which version to use in your HTML or CSS using media queries, viewport dimensions, and so on.

- Using MPEG4/WebM videos for animations and PNG/WebP for static images instead of GIF to save network bytes. 

- Remove unused Javascript, CSS, and images.

**What I observed:**

- On the contribute page, there is no way of going back to the home page. The link to the home page should be given in the logo to make the page user friendly.

**Comment by akshayadme** [comment]
Mobile Score is 40
Desktop Score is 81

- Basically PageSpeed Insight says to use low file size image in JPEG 2000, JPEG XR, and WebP formats for faster loading of website.

- In mobile view we can use some more navigations for better switching between programming languages. Because while we are on any article page and we want to switch to different article we have to go back and then we have to select which we have to read. So it will be frustrating for user.

- We are also using third party codes in our website and it also reduces the loading speed of website.

**Comment by imrushikesh** [comment]
#### Mobile Score -  67
#### Desktop Score -  92


- For desktop - For font files taking time to load and cache policy.
- for Mobile -  
       - instead of Gif use  MPEG4/WebM for animation. 
       - WebP for static Images.
       - Remove unused Javascript, CSS, and resize images.
       - Eliminate render-blocking resources. (linking in the head tag )
       - preload fonts and increase cache capacity.

_**Additional**_ -

- sponsor page doesn't have a link to the home page. Giving home link make it more accessible for the user.
