### ISSUE TITLE
Understanding SEO

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#2]
Explain what do you understand by SEO and why is it important, and how it's generally implemented in points. 
> Use links for reference if needed.

**Comment by akshayadme** [comment]
- SEO stands for Search Engine Optimization.

- SEO means a website containing html codes has to be organized in such a manner that it will achieve higher ranking in search engines research page (SERP) of search engine like Google, Yahoo, Bing and so on.

- By use of SEO more search engine users click on our website listing in the search engine results.

- SEO is important because it makes our website more visible to users that means our websites gets more traffic and more possibility that user will hit our website.

- To implement SEO in our website there are some of the key points we have to include in our web pages which are:- 

> 1. Title tag:- We have to use relevant keywords in our title tag that make more chances to tell search engines how they should rank our website.

> 2. Meta tag:- We must add some impactful description on meta tag that must not be more long it should be short and can describe the purpose of our web site in short.

> 3. Images:- If we are using images in our website then we should give it a appropriate alternate text this helps search engines find good images for their image search based on the keywords specified in it.

- There are lot more thing we should do to implement SEO in our website for that check this links:-

[A Simple Guide to SEO](https://neilpatel.com/blog/simple-guide-to-seo/)
[HTML tags for SEO](https://neilpatel.com/blog/html-tags-for-seo/)

-  We check our website SEO optimized or not we can go on [w3cvalidator](https://validator.w3.org/) for it. We can directly put our code in it and check for SEO.
